spring:
  application:
    name: conf-mq-con
  rabbitmq:
    host: 127.0.0.1
    password: 123
    port: 5672
    username: ityue
    virtual-host: /ityueca
    listener:
      simple:
        acknowledge-mode: manual #手动ACK
#        max-concurrency: 10 #消费之最大数量
#        concurrency: 1 #消费者最小数量
#        prefetch: 1 #在单个请求中处理的消息个数，他应该大于等于事务数量(unack的最大数量)
      direct:
        acknowledge-mode: manual #手动ACK